site_name: Alexander J. Hart

theme:
  name: material
  palette:
      primary: blue
      accent: orange
nav:
  - Home: index.md
  - Personal Projects:
    - Transmission System Study: projectsPersonal/TransmissionSystemStudy.md
#   - Academic Projects:
  - Resume: resume.md

markdown_extensions:
  - toc:
      toc_depth: 1

extra_css:
  - css/extra.css