site_name: Alexander J. Hart

theme:
  name: material
  palette:
      primary: blue
      accent: orange
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Personal Projects:
    - Transmission System Study: projectsPersonal/TransmissionSystemStudy.md
#   - Academic Projects:

markdown_extensions:
  - toc:
      toc_depth: 1
  - attr_list

plugins:
  - mkdocs-pdf

extra_css:
  - css/extra.css